version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./back-end:/app
    environment:
      - MONGODB_URI=mongodb://mongo:27017/app_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - mongo
      - redis
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    container_name: fastapi_worker
    volumes:
      - ./back-end:/app/back-end
      - ./worker:/app/worker
    environment:
      - MONGODB_URI=mongodb://mongo:27017/app_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - mongo
      - redis
      - rabbitmq

  frontend:
    image: node:20
    container_name: vite_frontend
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./front-end:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  mongo_data:
