[project]
name = "back-end"
version = "0.1.0"
description = "Playlist downloader back-end service"
readme = "README.md"
requires-python = "==3.13.4"
dependencies = [
    "celery==5.5.3",
    "fastapi[standard]==0.116.1",
    "redis==6.4.0",
    "uvicorn==0.37.0",
    "yt-dlp",
    "flower==2.0.0",
    "pymongo==4.15.2",
]
